name: Sync Fork

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  workflows: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the fork repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git config
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "actions@github.com"

    - name: Add upstream repository
      run: git remote add upstream https://github.com/Vendicated/Vencord.git

    - name: Sync with upstream
      run: |
        git fetch upstream
        git checkout main
        git reset --hard upstream/main

    - name: Push changes to fork repository
      run: git push origin main --force
